# -*- coding: utf-8 -*-
from operator import itemgetter

suffixs = []
suffixs.append(u'满族蒙古族锡伯族乡')
suffixs.append(u'土家族乡')
suffixs.append(u'回族街道办事处')
suffixs.append(u'畲族少数民族乡')
suffixs.append(u'回族满族乡')
suffixs.append(u'畲族乡')
suffixs.append(u'鄂伦春族民族乡')

suffixs.append(u'满族蒙古族乡')
suffixs.append(u'回族乡')
suffixs.append(u'满族乡')
suffixs.append(u'鄂温克民族乡')
suffixs.append(u'鄂温克族乡')
suffixs.append(u'朝鲜民族乡')
suffixs.append(u'达斡尔民族乡')
suffixs.append(u'达斡尔族乡')
suffixs.append(u'俄罗斯族民族乡')
suffixs.append(u'蒙古族满族乡')
suffixs.append(u'满族朝鲜族乡')
suffixs.append(u'朝鲜族满族乡')
suffixs.append(u'侗族乡')
suffixs.append(u'蒙古族乡')

suffixs.append(u'满族锡伯族镇')
suffixs.append(u'达斡尔族镇')
suffixs.append(u'蒙古族镇')
suffixs.append(u'满族镇')
suffixs.append(u'畲族镇')
suffixs.append(u'回族镇')
suffixs.append(u'维吾尔族回族乡')
suffixs.append(u'白族乡')
suffixs.append(u'壮族乡')
suffixs.append(u'壮族瑶族乡')
suffixs.append(u'仫佬族乡')
suffixs.append(u'瑶族苗族乡')
suffixs.append(u'苗族土家族乡')
suffixs.append(u'苗族仡佬族乡')
suffixs.append(u'土家族自治乡')
suffixs.append(u'彝族乡')
suffixs.append(u'傈僳族乡')
suffixs.append(u'苗族彝族乡')
suffixs.append(u'藏族乡')
suffixs.append(u'羌族乡')
suffixs.append(u'纳西族乡')
suffixs.append(u'傣族乡')
suffixs.append(u'布依族苗族乡')
suffixs.append(u'苗族布依族乡')
suffixs.append(u'布依族彝族乡')
suffixs.append(u'苗族彝族乡')
suffixs.append(u'苗族彝族布依族乡')
suffixs.append(u'彝族仡佬族布依族乡')
suffixs.append(u'彝族布依族苗族乡')
suffixs.append(u'苗族彝族回族乡')
suffixs.append(u'布依族乡')
suffixs.append(u'苗族布依族乡')
suffixs.append(u'布依族彝族苗族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'白族彝族苗族乡')
suffixs.append(u'布依族白族苗族乡')
suffixs.append(u'苗族彝族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'仡佬族苗族乡')
suffixs.append(u'苗族仡佬族乡')
suffixs.append(u'土家族乡')
suffixs.append(u'回族苗族乡')
suffixs.append(u'布依族苗族乡')
suffixs.append(u'苗族仡佬族乡')
suffixs.append(u'苗族彝族满族乡')
suffixs.append(u'彝族苗族布依族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'土家族苗族乡')
suffixs.append(u'侗族土家族苗族乡')
suffixs.append(u'水族乡')
suffixs.append(u'毛南族乡')
suffixs.append(u'彝族白族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'白族彝族乡')
suffixs.append(u'彝族傣族乡')
suffixs.append(u'彝族布朗族乡')
suffixs.append(u'布朗族彝族乡')
suffixs.append(u'彝族傈僳族乡')
suffixs.append(u'傣族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'回族彝族乡')
suffixs.append(u'回族彝族苗族乡')
suffixs.append(u'苗族彝族乡')
suffixs.append(u'彝族苗族乡')
suffixs.append(u'傈僳族彝族乡')
suffixs.append(u'彝族纳西族乡')
suffixs.append(u'傈僳族傣族乡')
suffixs.append(u'傈僳族普米族乡')
suffixs.append(u'彝族傣族乡')
suffixs.append(u'哈尼族乡')
suffixs.append(u'佤族乡')
suffixs.append(u'拉祜族乡')
suffixs.append(u'白族自治乡')
suffixs.append(u'傣族傈僳族自治乡')
suffixs.append(u'傣族自治乡')
suffixs.append(u'苗族壮族乡')
suffixs.append(u'傈僳族彝族乡')
suffixs.append(u'阿昌族乡')
suffixs.append(u'门巴民族乡')
suffixs.append(u'珞巴民族乡')
suffixs.append(u'东乡族乡')
suffixs.append(u'回族东乡族乡')
suffixs.append(u'东乡族乡')
suffixs.append(u'土族乡')
suffixs.append(u'蒙古族乡')
suffixs.append(u'回族民族乡')
suffixs.append(u'哈萨克民族乡')
suffixs.append(u'柯尔克孜族乡')
suffixs.append(u'塔吉克族乡')
suffixs.append(u'塔吉克民族乡')
suffixs.append(u'柯尔克孜民族乡')
suffixs.append(u'达斡尔民族乡')
suffixs.append(u'蒙古民族乡')
suffixs.append(u'回族维吾尔族乡')
suffixs.append(u'苗族瑶族乡')
suffixs.append(u'苗族侗族乡')
suffixs.append(u'苗族乡')
suffixs.append(u'侗族苗族乡')
suffixs.append(u'瑶族乡')

suffixs.append(u'街道办事处')
suffixs.append(u'地区办事处')
suffixs.append(u'民族乡')
suffixs.append(u'街道办')
suffixs.append(u'街道')
suffixs.append(u'镇')

suffixs = set(suffixs)
suffixs = list(suffixs)
suffixs = [(suffix, len(suffix)) for suffix in suffixs]

suffixs.sort(key=itemgetter(1, 0), reverse=True)

for suffix, count in suffixs:
    print suffix.encode('utf-8')

